#!/usr/bin/env bash
#
# Doc 14 section 5 step 4 / 11.5 -- write the bootstrap environment into the data directory.
# Linux equivalent of installer/configure-env.ps1.
#
# !! The one irreversible step in the whole installation. On an upgrade, every key that
# already exists is preserved, SECRET_STORE_KEY above all: regenerating it makes the existing
# secrets.enc.json undecryptable and destroys the operator's marketplace credentials with no
# way back. This script therefore only ever *adds* missing keys -- it never rewrites a value
# the operator or a previous install already put there.
#
# Only the values the wizard cannot change live here (doc 14 section 4.3). PORT, HOSTNAME,
# AUTO_MIGRATE, APP_VERSION and PLAYWRIGHT_BROWSERS_PATH are deployment facts and are set on
# the service instead (install-service.sh / the systemd unit), so a stale line in this file
# can never shadow what the installed service actually does.
set -euo pipefail

usage() { echo "Kullanim: $0 --data-dir DIR --install-dir DIR" >&2; exit 2; }

data_dir=""
install_dir=""
while [ $# -gt 0 ]; do
  case "$1" in
    --data-dir) data_dir="$2"; shift 2 ;;
    --install-dir) install_dir="$2"; shift 2 ;;
    *) usage ;;
  esac
done
[ -n "$data_dir" ] && [ -n "$install_dir" ] || usage

env_path="$data_dir/.env.local"
node_bin="$install_dir/node/bin/node"

mkdir -p "$data_dir"

# --- Read what is already there ----------------------------------------------------------------
declare -A existing=()
if [ -f "$env_path" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    trimmed="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [ -z "$trimmed" ] && continue
    case "$trimmed" in \#*) continue ;; esac
    if [[ "$trimmed" =~ ^([A-Z0-9_]+)=(.*)$ ]]; then
      existing["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
    fi
  done < "$env_path"
fi

# --- Fill in only what is missing ----------------------------------------------------------------
if [ -z "${existing[DATABASE_URL]:-}" ]; then
  # Absolute, not relative. The service's working directory *is* this data directory
  # (doc 14 section 4.1 / 11.3), so a relative path would resolve here too -- but Next's
  # generated server.js chdirs into the application directory while it boots, and a relative
  # path read during that window would silently create a second, empty database under
  # /opt/buybox. boot.mjs restores the working directory; this makes the database's location
  # independent of whether it did.
  existing[DATABASE_URL]="file:$data_dir/app.db"
fi

if [ -z "${existing[SECRET_STORE_KEY]:-}" ]; then
  # Generated by the bundled Node so there is one implementation of "random" in the product
  # (doc 14 section 4.3), and generated here so no two installs share a key.
  if [ ! -x "$node_bin" ]; then
    echo "SECRET_STORE_KEY uretilemedi: node bulunamadi ($node_bin); kurulum durduruldu." >&2
    exit 1
  fi
  key="$("$node_bin" -e "process.stdout.write(require('node:crypto').randomBytes(32).toString('hex'))")"
  if [ -z "$key" ]; then
    echo "SECRET_STORE_KEY uretilemedi; kurulum durduruldu." >&2
    exit 1
  fi
  existing[SECRET_STORE_KEY]="$key"
fi

[ -z "${existing[SECRET_STORE_PATH]:-}" ] && existing[SECRET_STORE_PATH]="$data_dir/secrets.enc.json"
[ -z "${existing[SINGLE_PROCESS]:-}" ] && existing[SINGLE_PROCESS]="1"

# --- Write back --------------------------------------------------------------------------------
tmp_path="$(mktemp "$data_dir/.env.local.XXXXXX")"
for k in "${!existing[@]}"; do
  printf '%s=%s\n' "$k" "${existing[$k]}"
done > "$tmp_path"
mv "$tmp_path" "$env_path"

# The file holds the key that protects every marketplace credential. Owned by, and readable
# only by, the buybox service user -- the interactive/login user has no reason to read it and
# no reason to be able to. The Linux equivalent of configure-env.ps1's ACL lockdown to SYSTEM
# and Administrators.
if id -u buybox >/dev/null 2>&1; then
  chown buybox:buybox "$env_path"
fi
chmod 600 "$env_path"

echo "Yapilandirma yazildi: $env_path"
