/**
 * The vendor's Ed25519 licence-signing public key (docs/13-licensing.md §2).
 *
 * This is a *public* key: it verifies licences and cannot issue them. The matching private key
 * is generated by `scripts/generate-license-keypair.mjs` into the gitignored `.license-keys/`
 * directory and must never appear in this repository.
 *
 * Rotating this constant invalidates every licence already in the field at once, so it is a
 * last resort (key compromise), not routine maintenance.
 */
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEASllSbrOWiIhz3zvWzJU2340rQ0JcrDp5R6kb+IVyUiE=
-----END PUBLIC KEY-----
`;

/**
 * Development override. Lets a developer point a local build at a throwaway keypair without
 * editing the constant above and risking a commit of it. Absent in every real install — and
 * deliberately harmless if an operator sets it, since substituting a public key is no easier
 * than editing the source they already hold (doc 13 §1).
 */
export function resolveLicensePublicKey(env: Record<string, string | undefined>): string {
  return env.LICENSE_PUBLIC_KEY_PEM ?? LICENSE_PUBLIC_KEY_PEM;
}
