<#
  Doc 14 section 5 step 4 -- write the bootstrap environment into the data directory.

  !! The one irreversible step in the whole installation. On an upgrade, every key that already
  exists is preserved, `SECRET_STORE_KEY` above all: regenerating it makes the existing
  `secrets.enc.json` undecryptable and destroys the operator's marketplace credentials with no
  way back. This script therefore only ever *adds* missing keys -- it never rewrites a value the
  operator or a previous install already put there.

  Only the values the wizard cannot change live here (doc 14 section 4.3). `PORT`, `HOSTNAME`,
  `AUTO_MIGRATE`, `APP_VERSION` and `PLAYWRIGHT_BROWSERS_PATH` are deployment facts and are set
  on the service instead (`install-service.ps1`), so a stale line in this file can never shadow
  what the installed service actually does.
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory)] [string] $DataDir,
  [Parameter(Mandatory)] [string] $InstallDir
)

$ErrorActionPreference = 'Stop'

$envPath = Join-Path $DataDir '.env.local'
$nodeExe = Join-Path $InstallDir 'node\node.exe'

if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }

# --- Read what is already there ----------------------------------------------------------------
$existing = [ordered]@{}
if (Test-Path $envPath) {
  foreach ($line in Get-Content $envPath) {
    $trimmed = $line.Trim()
    if ($trimmed -eq '' -or $trimmed.StartsWith('#')) { continue }
    $match = [regex]::Match($trimmed, '^([A-Z0-9_]+)=(.*)$')
    if ($match.Success) { $existing[$match.Groups[1].Value] = $match.Groups[2].Value }
  }
}

# --- Fill in only what is missing ----------------------------------------------------------------
if (-not $existing.Contains('DATABASE_URL')) {
  # Absolute, not relative. The service's working directory *is* this data directory (doc 14
  # section 4.1), so a relative path would resolve here too -- but Next's generated server.js chdirs
  # into the application directory while it boots, and a relative path read during that window
  # would silently create a second, empty database under Program Files. boot.mjs restores the
  # working directory; this makes the database independent of whether it did.
  $existing['DATABASE_URL'] = "file:$(Join-Path $DataDir 'app.db')"
}

if (-not $existing.Contains('SECRET_STORE_KEY')) {
  # Generated by the bundled Node so there is one implementation of "random" in the product
  # (doc 14 section 4.3), and generated here so no two installs share a key.
  $key = & $nodeExe -e "process.stdout.write(require('node:crypto').randomBytes(32).toString('hex'))"
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($key)) {
    throw 'SECRET_STORE_KEY uretilemedi; kurulum durduruldu.'
  }
  $existing['SECRET_STORE_KEY'] = $key
}

if (-not $existing.Contains('SECRET_STORE_PATH')) { $existing['SECRET_STORE_PATH'] = (Join-Path $DataDir 'secrets.enc.json') }
if (-not $existing.Contains('SINGLE_PROCESS')) { $existing['SINGLE_PROCESS'] = '1' }

# --- Write back --------------------------------------------------------------------------------
$lines = foreach ($k in $existing.Keys) { "$k=$($existing[$k])" }
Set-Content -Path $envPath -Value $lines -Encoding utf8

# The file holds the key that protects every marketplace credential. Administrators and SYSTEM
# only -- the interactive user has no reason to read it and no reason to be able to.
$acl = Get-Acl $envPath
$acl.SetAccessRuleProtection($true, $false)
$acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }
foreach ($account in @('NT AUTHORITY\SYSTEM', 'BUILTIN\Administrators')) {
  $rule = New-Object Security.AccessControl.FileSystemAccessRule($account, 'FullControl', 'Allow')
  $acl.AddAccessRule($rule)
}
Set-Acl -Path $envPath -AclObject $acl

Write-Output "Yapilandirma yazildi: $envPath"
